#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

NC='\033[0m'
BGRed='\033[0;41m'
BGreen='\033[30;42m'
BIYellow="\033[1;93m"
BIBlack="\033[1;90m"


# Rodar o phpstan

echo "\n\n${BIYellow} ⚗️ Fazendo análise estática... ${NC}\n"
./vendor/bin/phpstan
if [ $? -ne 0 ];
then
    echo "${BGreen} Erros foram encontrados no PHPStan. Corrija antes de continuar... 👮🏽 ${NC}";
    exit 1;
fi;

# rodar os testes
echo "${BIYellow} 📋 Rodando testes... ${NC}\n"
if ! php artisan test --parallel --stop-on-failure --testdox;
then
    echo "\n\n${BGRed}                                                                      ${NC}";
    echo "${BGRed} Opa! os testes encontraram erros. Corrija antes de continuar... 👮🏽 ${NC}";
    echo "${BGRed}                                                                      ${NC}\n\n";
    exit 1;
fi;

# Formatar cada arquivo alterado usando o Laravel Pint
echo "\n\n${BIYellow} 🎨 Formatando código... ${NC}\n"
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGED_FILES
do
    ./vendor/bin/pint "${FILE}" > /dev/null >&1;
    git add "${FILE}";
done;

echo "\n\n${BGreen}                                    ${NC}";
echo "${BGreen} Tudo certo! Push autorizado 👮🏽🎉 ${NC}";
echo "${BGreen}                                    ${NC}\n\n";
exit 0;
